model: "resnet2d18"
dataset: "ptbxl"
single_run_dir: ${hydra:run.dir}

df_path:
  ptbxl:
    train_directory: "E:/Work/PTB_XL/tesla_datasets/train_split_map_ptbxl.csv"
    valid_directory: "E:/Work/PTB_XL/tesla_datasets/valid_split_map_ptbxl.csv"
    test_directory: "E:/Work/PTB_XL/tesla_datasets/test_map_ptbxl.csv"

training_params:
  folds: 5
  batch_size: 16
  lr: 0.003
  epochs: 200

predict:
  checkpoint_path: ""

task_params:
  pathology_names: ["AFIB"]
  merge_map: {}

ecg_record_params:
  input_type: "2d"
  base: "E:/Work/PTB_XL/spectrograms"
  size: [512, 1536]