model: "resnet1d18"
train_df_path: "E:/Work/PTB_XL/tesla_datasets/train_split_map_ptbxl.csv"

training_params:
  folds: 5
  batch_size: 32
  lr: 0.003

task_params:
  pathology_names: ["AFIB"]
  merge_map: {}

ecg_record_params:
  input_type: "1d"
  base: ""
  size: [512, 1536]