mode: "federated_train" # train, federated_train, test

single_run_dir: ${hydra:run.dir}

dataset_path: "/home/khachaturov/MSU/diploma_IV/dataset/clients_dataset.csv"

device: "cuda"
device_ids: [0]

random_state: 42

training_params:
    learning_rate: 0.003
    epochs: 200
    early_stopping_patience: 10
    batch_size: 32
    num_workers: 4

federated_params:
    method: "FedAvg" # FedAvg, FedProx, FLTrust, FLTrust_new
    communication_rounds: 20
    clients_num: 5
    round_epochs: 5

    attack: True
    amount_of_attackers: 0.5
    percent_of_changed_labels: 0.7

    server_dataset: "/home/khachaturov/MSU/diploma_IV/dataset/server_dataset.csv"
    test_dataset: "/home/khachaturov/MSU/diploma_IV/dataset/test_dataset.csv"
    fltrust_new_sample_amount: 50